# -*- coding: utf-8 -*-
"""Copy of Task1_Numbers_ShadowFox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSpAc3cQlIk86vXq2I9sCJzyKduIwEc0
"""

#Format function
def format_sring(a,b):
   result="{} {}".format(a,b)
   return result

   print("formatted output:",format_string(145,'o'))

#pond area and water volume
radius=84
pi=3.14
Area=pi*(radius**2)

print("Area of pond(m^2):",
  int(Area)) #No decimal

      #Bonus:Total water in liters
water_per_sq_meter = 1.4
total_water = Area * water_per_sq_meter
print("Total water in pond(liters):",int(total_water))

#Speed calculation
distance_meters = 490
time_minutes = 7
time_seconds = time_minutes * 60

speed = distance_meters  / time_seconds #Integer division for no decimals

print("Speed(m/s):",speed)

