# -*- coding: utf-8 -*-
"""Task_Forloop_ShadowFox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13820Yqgw0AkPul3g7LHB4TGFM0VGlpMD
"""

#Dice Roll simulation
import random

rolls = 20
count_6 = 0
count_1 = 0
double_6 = 0
previous_roll = 0

for i in range(rolls):
    roll = random.randint(1, 6)
    print(f"Roll {i+1}: {roll}")

    if roll == 6:
        count_6 += 1
        if previous_roll == 6:
            double_6 += 1
    if roll == 1:
        count_1 += 1

    previous_roll = roll

print(f"Total times rolled 6: {count_6}")
print(f"Total times rolled 1: {count_1}")
print(f"Two 6s in a row: {double_6}")

total = 100
done = 0
set_size = 10

while done < total:
    done += set_size
    print(f"You completed {done} jumping jacks.")

    if done >= total:
        print("Congratulations! You completed the workout.")
        break

    tired = input("Are you tired? (yes/no): ").lower()

    if tired in ["yes", "y"]:
        skip = input("Do you want to skip the remaining sets? (yes/no): ").lower()
        if skip in ["yes", "y"]:
            print(f"You completed a total of {done} jumping jacks.")
            break

